project:
  type: website
  output-dir: _site

website:
  title: "Gregory Ehlinger"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - blog.qmd
      - projects.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

